
vae_type: VQVAE
scale_factor: 1.0


enc_dec_dict:    
    resolution: 128
    in_channels: 3
    z_channels: 3
    ch: 64
    ch_mult: [1, 2, 4]       # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: []
    out_ch: 4
    dropout: 0.0

vq_dict:
    n_embed: 4096            # vocab_size
    embed_dim: 3             # same as `z_channels`
    percept_loss_w: 1.0

